In [1]:
import numpy as np

In [2]:
#Create an array
arr = np.arange(5)

In [3]:
#Saving array on disk in binary format (file extension .npy)
np.save('my_array',arr)

In [4]:
#Change arr
arr = np.arange(10)
#Show
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
#Lets see the original saved copy
np.load('my_array.npy')

array([0, 1, 2, 3, 4])

In [6]:
#Saving multiple arrays into a zip file
np.savez('two_arrays.npz',x=arr,y=arr)

#Now loading multiple arrays
archive_array = np.load('two_arrays.npz')

#Show
archive_array['x']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
#Now lets remove them from the memory
rm my_array.npy
rm two_arrays.npz

SyntaxError: invalid syntax (<ipython-input-7-70bf7d7c98da>, line 2)

In [ ]:
#Now saving and loading text files

arr = np.array([[1,2,3],[4,5,6]])
np.savetxt('my_test_text.txt',arr,delimiter=',')

In [ ]:
arr = np.loadtxt('my_test_text.txt',delimiter = ',')
arr